"""Initial

Revision ID: 9c702a28fbc0
Revises: 
Create Date: 2026-09-18 06:01:51.430696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c702a28fbc0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_products',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('subcategory', sa.String(), nullable=True),
    sa.Column('unit_type', sa.Enum('PIECE', 'KG', 'LITRE', 'BOX', 'PACK', name='unittype'), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_global_products')),
    sa.UniqueConstraint('sku', name=op.f('uq_global_products_sku'))
    )
    op.create_index(op.f('ix_global_products_barcode'), 'global_products', ['barcode'], unique=True)
    op.create_table('organizations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('RETAILER', 'WHOLESALER', name='organizationtype'), nullable=False),
    sa.Column('legal_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('inn', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', name='organizationstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('inn', name=op.f('uq_organizations_inn'))
    )
    op.create_table('branches',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_branches_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches'))
    )
    op.create_table('orders',
    sa.Column('order_number', sa.String(), nullable=False),
    sa.Column('retailer_branch_id', sa.UUID(), nullable=False),
    sa.Column('wholesaler_branch_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'DISPATCHED', 'DELIVERED', 'PARTIALLY_RETURNED', 'COMPLETED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('delivery_type', sa.Enum('SELF_PICKUP', 'WHOLESALER_DELIVERY', name='deliverytype'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['retailer_branch_id'], ['branches.id'], name=op.f('fk_orders_retailer_branch_id_branches')),
    sa.ForeignKeyConstraint(['wholesaler_branch_id'], ['branches.id'], name=op.f('fk_orders_wholesaler_branch_id_branches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_table('pos_sale_ledger',
    sa.Column('retailer_branch_id', sa.UUID(), nullable=False),
    sa.Column('global_product_id', sa.UUID(), nullable=False),
    sa.Column('qty_sold', sa.Integer(), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['global_product_id'], ['global_products.id'], name=op.f('fk_pos_sale_ledger_global_product_id_global_products')),
    sa.ForeignKeyConstraint(['retailer_branch_id'], ['branches.id'], name=op.f('fk_pos_sale_ledger_retailer_branch_id_branches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pos_sale_ledger'))
    )
    op.create_table('retailer_inventory',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('global_product_id', sa.UUID(), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('safety_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('auto_reorder_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_retailer_inventory_branch_id_branches')),
    sa.ForeignKeyConstraint(['global_product_id'], ['global_products.id'], name=op.f('fk_retailer_inventory_global_product_id_global_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retailer_inventory')),
    sa.UniqueConstraint('branch_id', 'global_product_id', name=op.f('uq_retailer_inventory_branch_id'))
    )
    op.create_table('users',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('SUPERADMIN', 'WHOLESALER_ADMIN', 'WHOLESALER_MANAGER', 'RETAILER_ADMIN', 'RETAILER_STAFF', 'DRIVER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_users_branch_id_branches')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('wholesaler_inventory',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('global_product_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('moq', sa.Integer(), nullable=False),
    sa.Column('available_stock', sa.Integer(), nullable=False),
    sa.Column('reserved_stock', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_wholesaler_inventory_branch_id_branches')),
    sa.ForeignKeyConstraint(['global_product_id'], ['global_products.id'], name=op.f('fk_wholesaler_inventory_global_product_id_global_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wholesaler_inventory')),
    sa.UniqueConstraint('branch_id', 'global_product_id', name=op.f('uq_wholesaler_inventory_branch_id'))
    )
    op.create_table('billing_ledger',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.Enum('DEBIT_FEE', 'CREDIT_PAYMENT', 'ADJUSTMENT', name='transactiontype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reference_order_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_billing_ledger_organization_id_organizations')),
    sa.ForeignKeyConstraint(['reference_order_id'], ['orders.id'], name=op.f('fk_billing_ledger_reference_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_ledger'))
    )
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('global_product_id', sa.UUID(), nullable=False),
    sa.Column('ordered_qty', sa.Integer(), nullable=False),
    sa.Column('delivered_qty', sa.Integer(), nullable=False),
    sa.Column('returned_qty', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['global_product_id'], ['global_products.id'], name=op.f('fk_order_items_global_product_id_global_products')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    op.create_table('return_acts',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('photo_proof_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'ACCEPTED', 'DISPUTED', name='returnactstatus'), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('return_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_return_acts_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_return_acts'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('return_acts')
    op.drop_table('order_items')
    op.drop_table('billing_ledger')
    op.drop_table('wholesaler_inventory')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_table('retailer_inventory')
    op.drop_table('pos_sale_ledger')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('branches')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_global_products_barcode'), table_name='global_products')
    op.drop_table('global_products')
    # ### end Alembic commands ###
